name: Cache Assets

on:
  schedule:
    - cron: '0 */12 * * *'  # every 12 hours
  workflow_dispatch:

jobs:
  cache-readme-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache dynamic images
        run: |
          mkdir -p assets

          curl -L "https://github-readme-stats.vercel.app/api?username=varshney565&show_icons=true&theme=radical" -o assets/github-stats.svg
          curl -L "https://github-readme-streak-stats.herokuapp.com/?user=varshney565&theme=radical" -o assets/github-streak.svg
          curl -L "https://github-readme-stats.vercel.app/api/top-langs?username=varshney565&layout=compact&theme=radical" -o assets/top-langs.svg
          curl -L "https://github-profile-trophy.vercel.app/?username=varshney565&theme=onedark&margin-w=10&margin-h=10&row=1" -o assets/trophies.svg

      - name: Commit cached images
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add assets/*.svg
          git commit -m "chore: update cached assets" || echo "No changes"
          git push
