name: cache-cards

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"  # daily at 18:00 UTC

permissions:
  contents: write

jobs:
  cache:
    runs-on: ubuntu-latest
    env:
      GH_USER: varshney565

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure assets dir
        run: mkdir -p assets

      - name: GitHub stats
        shell: bash
        run: |
          set -euo pipefail
          OUT="assets/github-stats.svg"; TMP="${OUT}.tmp"
          curl -fsSL --retry 7 --retry-delay 6 "https://github-readme-stats.vercel.app/api?username=${GH_USER}&show_icons=true&include_all_commits=true&count_private=true&cache_seconds=43200&theme=tokyonight" -o "$TMP" || true
          if [ -s "$TMP" ] && head -c 5 "$TMP" | grep -qi '<svg'; then mv "$TMP" "$OUT"; else rm -f "$TMP"; fi
          [ -s "$OUT" ] || printf '<svg xmlns="http://www.w3.org/2000/svg" width="700" height="200"><rect width="100%%" height="100%%" fill="#0d1117"/><text x="50%%" y="50%%" fill="#58a6ff" font-size="16" font-family="Arial" text-anchor="middle" dominant-baseline="middle">Temporarily unavailable — will refresh on next run</text></svg>' > "$OUT"

      - name: Streak
        shell: bash
        run: |
          set -euo pipefail
          OUT="assets/github-streak.svg"; TMP="${OUT}.tmp"
          curl -fsSL --retry 7 --retry-delay 6 "https://streak-stats.demolab.com?user=${GH_USER}&theme=tokyonight" -o "$TMP" || true
          if [ -s "$TMP" ] && head -c 5 "$TMP" | grep -qi '<svg'; then mv "$TMP" "$OUT"; else rm -f "$TMP"; fi
          [ -s "$OUT" ] || printf '<svg xmlns="http://www.w3.org/2000/svg" width="700" height="200"><rect width="100%%" height="100%%" fill="#0d1117"/><text x="50%%" y="50%%" fill="#58a6ff" font-size="16" font-family="Arial" text-anchor="middle" dominant-baseline="middle">Temporarily unavailable — will refresh on next run</text></svg>' > "$OUT"

      - name: Top languages
        shell: bash
        run: |
          set -euo pipefail
          OUT="assets/top-langs.svg"; TMP="${OUT}.tmp"
          curl -fsSL --retry 7 --retry-delay 6 "https://github-readme-stats.vercel.app/api/top-langs/?username=${GH_USER}&layout=compact&langs_count=10&cache_seconds=43200&theme=tokyonight" -o "$TMP" || true
          if [ -s "$TMP" ] && head -c 5 "$TMP" | grep -qi '<svg'; then mv "$TMP" "$OUT"; else rm -f "$TMP"; fi
          [ -s "$OUT" ] || printf '<svg xmlns="http://www.w3.org/2000/svg" width="700" height="200"><rect width="100%%" height="100%%" fill="#0d1117"/><text x="50%%" y="50%%" fill="#58a6ff" font-size="16" font-family="Arial" text-anchor="middle" dominant-baseline="middle">Temporarily unavailable — will refresh on next run</text></svg>' > "$OUT"

      - name: Typing line
        shell: bash
        run: |
          set -euo pipefail
          OUT="assets/typing.svg"; TMP="${OUT}.tmp"
          curl -fsSL --retry 5 --retry-delay 5 "https://readme-typing-svg.demolab.com?font=Inter&weight=700&size=24&pause=900&duration=2600&color=00FFFF&center=true&vCenter=true&width=700&lines=Blockchain+Developer;Backend:+Rust+%7C+Go+%7C+Node.js;Competitive+Programmer" -o "$TMP" || true
          if [ -s "$TMP" ] && head -c 5 "$TMP" | grep -qi '<svg'; then mv "$TMP" "$OUT"; else rm -f "$TMP"; fi
          [ -s "$OUT" ] || printf '<svg xmlns="http://www.w3.org/2000/svg" width="700" height="40"><rect width="100%%" height="100%%" fill="#0d1117"/><text x="50%%" y="50%%" fill="#58a6ff" font-size="16" font-family="Arial" text-anchor="middle" dominant-baseline="middle">Blockchain Developer · Backend · Competitive Programmer</text></svg>' > "$OUT"

      - name: Trophies (advanced)
        shell: bash
        run: |
          set -euo pipefail
          OUT="assets/trophies-advanced.svg"; TMP="${OUT}.tmp"
          curl -fsSL --retry 5 --retry-delay 5 "https://github-profile-trophy.vercel.app/?username=${GH_USER}&theme=matrix&no-bg=true&no-frame=true&column=6" -o "$TMP" || true
          if [ -s "$TMP" ] && head -c 5 "$TMP" | grep -qi '<svg'; then mv "$TMP" "$OUT"; else rm -f "$TMP"; fi
          [ -s "$OUT" ] || printf '<svg xmlns="http://www.w3.org/2000/svg" width="920" height="160"><rect width="100%%" height="100%%" fill="#0d1117"/><text x="50%%" y="50%%" fill="#58a6ff" font-size="16" font-family="Arial" text-anchor="middle" dominant-baseline="middle">Trophies will load after next run</text></svg>' > "$OUT"

      - name: Commit cached cards
        shell: bash
        run: |
          if [ -n "$(git status --porcelain assets)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add assets/*.svg
            git commit -m "chore: refresh cached README cards"
            git push
          else
            echo "No card changes"
          fi
